# Generated by Django 3.0.6 on 2020-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlevel',
            name='RepaymentPeriod',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
