# Generated by Django 3.0.6 on 2020-06-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ID', models.CharField(max_length=100, verbose_name='贷款ID')),
                ('gender', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='年龄')),
                ('income', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='年收入')),
                ('income_source', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='收入来源')),
                ('job', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='工作类别')),
                ('job_history', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='工作年限')),
                ('edu', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='教育水平')),
                ('marry', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='婚姻状况')),
                ('is_Email', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否有电子邮箱')),
                ('is_WorkTel', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否有工作电话')),
                ('is_Tel', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否有手机')),
                ('is_Car', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否有车')),
                ('Child_Num', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='孩子数量')),
                ('live_addr', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='居住方式')),
                ('Fam_Num', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='家庭成员数量')),
                ('is_Asset', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否有固定资产')),
                ('is_Break', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='是否违约')),
                ('credit_score', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='信用分')),
            ],
            options={
                'verbose_name': '贷款额度审核',
                'verbose_name_plural': '贷款额度审核',
            },
        ),
        migrations.AlterModelOptions(
            name='anti_fraud_yes',
            options={'verbose_name': '欺诈申请队列', 'verbose_name_plural': '欺诈申请队列'},
        ),
    ]
