# Generated by Django 3.0.6 on 2020-08-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0002_creditlevel_repaymentperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditlevel',
            old_name='RepaymentPeriod',
            new_name='repaymentPeriod',
        ),
    ]
