# Generated by Django 3.0.6 on 2020-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0003_auto_20200824_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlevel',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
