# Generated by Django 3.0.6 on 2020-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0004_afterloan_behaviorscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterloan',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='behaviorscore',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='label'),
        ),
    ]
