# Generated by Django 3.0.6 on 2020-07-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approval', '0006_auto_20200702_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='anti_fraud_yes',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='是否通过反欺诈模型'),
        ),
    ]
